tasks:
  - init: |
      echo 'TODO: build project'
    command: |
      docker run --name my-iris -p 52773:52773 -it ramb0/cloudstudio --check-caps false
ports:
  - port: 52777
    visibility: public
